version: '3'

services:
    passwordmanager:
        build:
            context: .
            dockerfile: docker/Dockerfile
        entrypoint: "/root/entrypoint.sh"
        ports:
            - "80:80"    
        env_file: configuration.env
    mariadb:
        image: mariadb:10.4
        ports:
            - '3306:3306'
        volumes:
            - db_data/var/lib/mysql
        env_file: configuration.env
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
